=== quantNebula/scrapedPoGo/schemas/eggs.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ayy-j/scrapedPoGo/main/schemas/eggs.schema.json",
  "title": "Pokemon GO Eggs Data",
  "description": "Schema for Pokemon GO egg hatch data from LeekDuck",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "name",
      "eggType",
      "isAdventureSync",
      "image",
      "canBeShiny",
      "combatPower",
      "isRegional",
      "isGiftExchange",
      "rarity",
      "imageWidth",
      "imageHeight",
      "imageType"
    ],
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the hatched Pokemon"
      },
      "eggType": {
        "type": "string",
        "description": "The type of the egg",
        "enum": ["1 km", "2 km", "5 km", "7 km", "10 km", "12 km"]
      },
      "isAdventureSync": {
        "type": "boolean",
        "description": "Whether or not the egg is obtained from Adventure Sync"
      },
      "image": {
        "type": "string",
        "format": "uri",
        "description": "The image URL of the hatched Pokemon"
      },
      "canBeShiny": {
        "type": "boolean",
        "description": "Whether or not the hatched Pokemon can be shiny"
      },
      "combatPower": {
        "type": "object",
        "description": "The combat power range of the hatched Pokemon",
        "required": ["min", "max"],
        "properties": {
          "min": {
            "type": "integer",
            "description": "The minimum combat power of the hatched Pokemon"
          },
          "max": {
            "type": "integer",
            "description": "The maximum combat power of the hatched Pokemon"
          }
        },
        "additionalProperties": false
      },
      "isRegional": {
        "type": "boolean",
        "description": "Whether or not the hatched Pokemon is a regional exclusive"
      },
      "isGiftExchange": {
        "type": "boolean",
        "description": "Whether or not the egg is obtained from gift exchange"
      },
      "rarity": {
        "type": "integer",
        "description": "The rarity tier of the hatched Pokemon (1-5 scale)",
        "minimum": 1,
        "maximum": 5
      },
      "imageWidth": {
        "type": "integer",
        "description": "The width of the image in pixels"
      },
      "imageHeight": {
        "type": "integer",
        "description": "The height of the image in pixels"
      },
      "imageType": {
        "type": "string",
        "description": "The image format",
        "enum": ["png", "jpg", "jpeg", "gif", "webp"]
      }
    },
    "additionalProperties": false
  }
}

=== quantNebula/scrapedPoGo/data/eggs.min.json
[{"name":"Bulbasaur","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm1.icon.png","canBeShiny":true,"combatPower":{"min":637,"max":637},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":107,"imageHeight":126,"imageType":"png"},{"name":"Charmander","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm4.icon.png","canBeShiny":true,"combatPower":{"min":560,"max":560},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":91,"imageHeight":110,"imageType":"png"},{"name":"Squirtle","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm7.icon.png","canBeShiny":true,"combatPower":{"min":540,"max":540},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":95,"imageHeight":101,"imageType":"png"},{"name":"Chikorita","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm152.icon.png","canBeShiny":true,"combatPower":{"min":534,"max":534},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":57,"imageHeight":115,"imageType":"png"},{"name":"Cyndaquil","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm155.icon.png","canBeShiny":true,"combatPower":{"min":560,"max":560},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":86,"imageHeight":99,"imageType":"png"},{"name":"Totodile","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm158.icon.png","canBeShiny":true,"combatPower":{"min":646,"max":646},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":99,"imageHeight":113,"imageType":"png"},{"name":"Treecko","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm252.icon.png","canBeShiny":true,"combatPower":{"min":601,"max":601},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":85,"imageHeight":108,"imageType":"png"},{"name":"Torchic","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm255.icon.png","canBeShiny":true,"combatPower":{"min":624,"max":624},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":54,"imageHeight":103,"imageType":"png"},{"name":"Mudkip","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm258.icon.png","canBeShiny":true,"combatPower":{"min":644,"max":644},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":68,"imageHeight":100,"imageType":"png"},{"name":"Turtwig","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm387.icon.png","canBeShiny":true,"combatPower":{"min":678,"max":678},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":68,"imageHeight":101,"imageType":"png"},{"name":"Chimchar","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm390.icon.png","canBeShiny":true,"combatPower":{"min":547,"max":547},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":62,"imageHeight":108,"imageType":"png"},{"name":"Piplup","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm393.icon.png","canBeShiny":true,"combatPower":{"min":614,"max":614},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":88,"imageHeight":99,"imageType":"png"},{"name":"Snivy","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm495.icon.png","canBeShiny":true,"combatPower":{"min":485,"max":485},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":82,"imageHeight":79,"imageType":"png"},{"name":"Tepig","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm498.icon.png","canBeShiny":true,"combatPower":{"min":618,"max":618},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":79,"imageHeight":111,"imageType":"png"},{"name":"Oshawott","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm501.icon.png","canBeShiny":true,"combatPower":{"min":597,"max":597},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":91,"imageHeight":108,"imageType":"png"},{"name":"Chespin","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm650.icon.png","canBeShiny":true,"combatPower":{"min":626,"max":626},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":80,"imageHeight":112,"imageType":"png"},{"name":"Fennekin","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm653.icon.png","canBeShiny":true,"combatPower":{"min":587,"max":587},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":100,"imageHeight":112,"imageType":"png"},{"name":"Froakie","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm656.icon.png","canBeShiny":true,"combatPower":{"min":567,"max":567},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":89,"imageHeight":100,"imageType":"png"},{"name":"Rowlet","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm722.icon.png","canBeShiny":true,"combatPower":{"min":604,"max":604},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":81,"imageHeight":94,"imageType":"png"},{"name":"Litten","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm725.icon.png","canBeShiny":true,"combatPower":{"min":591,"max":591},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":95,"imageHeight":121,"imageType":"png"},{"name":"Popplio","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm728.icon.png","canBeShiny":true,"combatPower":{"min":645,"max":645},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":108,"imageHeight":98,"imageType":"png"},{"name":"Grookey","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm810.icon.png","canBeShiny":false,"combatPower":{"min":620,"max":620},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":75,"imageHeight":97,"imageType":"png"},{"name":"Scorbunny","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm813.icon.png","canBeShiny":false,"combatPower":{"min":627,"max":627},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":60,"imageHeight":113,"imageType":"png"},{"name":"Sobble","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm816.icon.png","canBeShiny":false,"combatPower":{"min":627,"max":627},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":64,"imageHeight":98,"imageType":"png"},{"name":"Sprigatito","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm906.icon.png","canBeShiny":true,"combatPower":{"min":579,"max":579},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":66,"imageHeight":99,"imageType":"png"},{"name":"Fuecoco","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm909.icon.png","canBeShiny":true,"combatPower":{"min":644,"max":644},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":75,"imageHeight":103,"imageType":"png"},{"name":"Quaxly","eggType":"1 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm912.icon.png","canBeShiny":true,"combatPower":{"min":614,"max":614},"isRegional":false,"isGiftExchange":false,"rarity":4,"imageWidth":75,"imageHeight":105,"imageType":"png"},{"name":"Bonsly","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm438.icon.png","canBeShiny":true,"combatPower":{"min":744,"max":744},"isRegional":false,"isGiftExchange":false,"rarity":1,"imageWidth":66,"imageHeight":107,"imageType":"png"},{"name":"Ducklett","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm580.icon.png","canBeShiny":true,"combatPower":{"min":489,"max":489},"isRegional":false,"isGiftExchange":false,"rarity":1,"imageWidth":72,"imageHeight":103,"imageType":"png"},{"name":"Litleo","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm667.icon.png","canBeShiny":true,"combatPower":{"min":814,"max":814},"isRegional":false,"isGiftExchange":false,"rarity":1,"imageWidth":94,"imageHeight":121,"imageType":"png"},{"name":"Smoliv","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm928.icon.png","canBeShiny":true,"combatPower":{"min":488,"max":488},"isRegional":false,"isGiftExchange":false,"rarity":1,"imageWidth":68,"imageHeight":91,"imageType":"png"},{"name":"Meditite","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm307.icon.png","canBeShiny":true,"combatPower":{"min":396,"max":396},"isRegional":false,"isGiftExchange":false,"rarity":3,"imageWidth":97,"imageHeight":115,"imageType":"png"},{"name":"Petilil","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm548.icon.png","canBeShiny":true,"combatPower":{"min":588,"max":588},"isRegional":false,"isGiftExchange":false,"rarity":3,"imageWidth":54,"imageHeight":94,"imageType":"png"},{"name":"Bergmite","eggType":"2 km","isAdventureSync":false,"image":"https://cdn.leekduck.com/assets/img/pokemon_icons_crop/pm712.icon
